name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Get Node PKG Cache dir
      id: node-pkg-cache
      run: |
        node -e "const path = require('path'); const fs = require('fs'); const cachePath = path.join(os.tmpdir(), 'pkg-cache'); fs.mkdirSync(cachePath); console.log('::set-output name=dir::' + cachePath)"
    - name: Cache driver
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: ${{ steps.node-pkg-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyee
    - name: Build driver
      run: python build_driver.py
      env:
        PKG_CACHE_PATH: ${{ steps.node-pkg-cache.outputs.dir }}
    - name: Build package
      run: python build_package.py
    - name: Test
      run: python -m unittest
