name: "publish canary docker"

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *"

jobs:
  publish-canary:
    name: "Publish canary Docker"
    runs-on: ubuntu-20.04
    if: github.repository == 'microsoft/playwright-python'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies & browsers
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r local-requirements.txt
        pip install -e .
    - uses: azure/docker-login@v1
      with:
        login-server: playwright.azurecr.io
        username: playwright
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker QEMU for arm64 docker builds
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - name: publish docker canary
      run: ./utils/docker/publish_docker.sh canary
