name: Test Docker
on:
  push:
    paths:
      - '.github/workflows/test_docker.yml'
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/test_docker.yml'
    branches:
      - main
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r local-requirements.txt
        pip install -e .
    - name: Build Docker image
      run: bash utils/docker/build.sh --amd64 focal playwright-python:localbuild-focal
    - name: Test
      run: |
        CONTAINER_ID="$(docker run --rm -v $(pwd):/root/playwright --name playwright-docker-test --workdir /root/playwright/ -d -t playwright-python:localbuild-focal /bin/bash)"
        docker exec "${CONTAINER_ID}" pip install -r local-requirements.txt
        docker exec "${CONTAINER_ID}" pip install -e .
        docker exec "${CONTAINER_ID}" python setup.py bdist_wheel
        docker exec "${CONTAINER_ID}" xvfb-run pytest -vv tests/sync/
        docker exec "${CONTAINER_ID}" xvfb-run pytest -vv tests/async/
